-- MySQL Script generated by MySQL Workbench
-- Wed May  9 18:53:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema systemdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `systemdb` ;

-- -----------------------------------------------------
-- Schema systemdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemdb` DEFAULT CHARACTER SET utf8 ;
USE `systemdb` ;

-- -----------------------------------------------------
-- Table `systemdb`.`USER_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`USER_STATUS` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`USER_STATUS` (
  `ID_USER_STATUS` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(45) NOT NULL,
  `OPIS` NVARCHAR(45) NULL,
  PRIMARY KEY (`ID_USER_STATUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`USER` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`USER` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `IME` NVARCHAR(20) NOT NULL,
  `PREZIME` NVARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(40) NOT NULL,
  `USERNAME` NVARCHAR(40) NOT NULL,
  `PASSWORD` NVARCHAR(40) NOT NULL,
  `POSLEDNJE_LOGOVANJE_KORISNIKA` DATETIME NULL,
  `FOTO_NAZIV` NVARCHAR(40) NULL,
  `USER_STATUS` INT NOT NULL,
  PRIMARY KEY (`ID_USER`),
  INDEX `fk_USER_USER_STATUS1_idx` (`USER_STATUS` ASC),
  CONSTRAINT `fk_USER_USER_STATUS1`
    FOREIGN KEY (`USER_STATUS`)
    REFERENCES `systemdb`.`USER_STATUS` (`ID_USER_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`PRIJAVA_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`PRIJAVA_STATUS` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`PRIJAVA_STATUS` (
  `ID_STATUS` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(45) NOT NULL,
  `OPIS` NVARCHAR(45) NULL,
  PRIMARY KEY (`ID_STATUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`SMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`SMER` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`SMER` (
  `ID_SMER` INT NOT NULL AUTO_INCREMENT,
  `NAZIV_SMERA` NVARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID_SMER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`USER_SMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`USER_SMER` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`USER_SMER` (
  `ID_SMER` INT NOT NULL,
  `ID_USER` INT NOT NULL,
  INDEX `fk_USER_SMER_SMER1_idx` (`ID_SMER` ASC),
  INDEX `fk_USER_SMER_USER1_idx` (`ID_USER` ASC),
  CONSTRAINT `fk_USER_SMER_SMER1`
    FOREIGN KEY (`ID_SMER`)
    REFERENCES `systemdb`.`SMER` (`ID_SMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_SMER_USER1`
    FOREIGN KEY (`ID_USER`)
    REFERENCES `systemdb`.`USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`GODINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`GODINA` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`GODINA` (
  `ID_GODINA` INT NOT NULL AUTO_INCREMENT,
  `SHKOLSKA_GODINA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_GODINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`PRIJAVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`PRIJAVA` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`PRIJAVA` (
  `ID_PRIJAVA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV_PRIJAVE` NVARCHAR(40) NOT NULL,
  `OD_KOG_DATUMA` DATETIME NOT NULL,
  `DO_KOG_DATUMA` DATETIME NOT NULL,
  `ID_STATUS` INT NOT NULL,
  PRIMARY KEY (`ID_PRIJAVA`),
  INDEX `fk_PRIJAVA_STATUS1_idx` (`ID_STATUS` ASC),
  CONSTRAINT `fk_PRIJAVA_STATUS1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `systemdb`.`PRIJAVA_STATUS` (`ID_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`GODINA_SMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`GODINA_SMER` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`GODINA_SMER` (
  `ID_SMER` INT NOT NULL,
  `GODINA_ID_GODINA` INT NOT NULL,
  INDEX `fk_GODINA_SMER_SMER1_idx` (`ID_SMER` ASC),
  INDEX `fk_GODINA_SMER_GODINA1_idx` (`GODINA_ID_GODINA` ASC),
  CONSTRAINT `fk_GODINA_SMER_SMER1`
    FOREIGN KEY (`ID_SMER`)
    REFERENCES `systemdb`.`SMER` (`ID_SMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GODINA_SMER_GODINA1`
    FOREIGN KEY (`GODINA_ID_GODINA`)
    REFERENCES `systemdb`.`GODINA` (`ID_GODINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdb`.`SMER_PRIJAVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemdb`.`SMER_PRIJAVA` ;

CREATE TABLE IF NOT EXISTS `systemdb`.`SMER_PRIJAVA` (
  `ID_PRIJAVA` INT NOT NULL,
  `ID_SMER` INT NOT NULL,
  INDEX `fk_SMER_PRIJAVA_PRIJAVA1_idx` (`ID_PRIJAVA` ASC),
  INDEX `fk_SMER_PRIJAVA_SMER1_idx` (`ID_SMER` ASC),
  CONSTRAINT `fk_SMER_PRIJAVA_PRIJAVA1`
    FOREIGN KEY (`ID_PRIJAVA`)
    REFERENCES `systemdb`.`PRIJAVA` (`ID_PRIJAVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SMER_PRIJAVA_SMER1`
    FOREIGN KEY (`ID_SMER`)
    REFERENCES `systemdb`.`SMER` (`ID_SMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
